### ISSUE TITLE
Do you have the load balance loss?

### ISSUE THREAD

**Issue by hobbitlzy** [renatoviolin/Switch-Transformers-in-Seq2Seq#1]
Hi, I read your codes and find there is no load balance loss defined in the [SwithFeedForward](https://github.com/renatoviolin/Switch-Transformers-in-Seq2Seq/blob/bda5d1412997b06565fd8b59fcf6aad944d18fb5/layers.py#L62). Have you checked how the tokens are distributed then?

Looking forward to your reply😁.

**Comment by agwaBom** [comment]
Well if you see the source code of [labmlai](https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/transformers/switch/__init__.py) which he/she referenced it is annotated as below.

"""
Our implementation only has a few million parameters and doesn't do model parallel distributed training.
It does single GPU training, but we implement the concept of switching as described in the paper.
...
In our implementation this doesn't parallelize well when you have many or large FFNs since it's all
happening on a single GPU.
"""

So I might think the load-balanced loss is not considered for this project too.

**Comment by hobbitlzy** [comment]
Thanks for your reply. If I understand right, labmlai writes because of  the training efficiency. I also think the load balance loss is important to the MoE algorithm. Since the training to each experts is a positive feedback, the more trained experts will be assigned more tokens. As a result, most of the experts will be ignored without the load balance loss.

**Comment by agwaBom** [comment]
Yes, I also agree with your opinion since load balancing loss is essential to distribute the data to be assigned to each expert evenly. So labmlai also mentioned that it will not parallelize well when you have many FFN i.e. experts.

**Comment by hobbitlzy** [comment]
Oh, I get your point. That is exactly what I want to make sure of. Thanks😁.
